language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - pip install --upgrade pip
  - pip install "setuptools>=28.6.1"
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls
  - pip install pytest-cov
script:
  - flake8 .
  - py.test
after_success:
  - coveralls
cache: pip
